using FinTrack.IdentityService.Data;
using Grpc.Core;
using Microsoft.EntityFrameworkCore;

namespace FinTrack.IdentityService.Services;

/// <summary>
/// gRPC server — WalletService calls GetUser() to verify a user exists
/// before creating a wallet. Binary Protobuf protocol, ~5x faster than REST.
/// The base class IdentityGrpcBase was generated by Grpc.Tools from identity.proto.
/// </summary>
public class IdentityGrpcService : FinTrack.Contracts.IdentityGrpc.IdentityGrpcBase
{
    private readonly IdentityDbContext _db;
    private readonly ILogger<IdentityGrpcService> _logger;

    public IdentityGrpcService(IdentityDbContext db, ILogger<IdentityGrpcService> logger)
    {
        _db     = db;
        _logger = logger;
    }

    public override async Task<FinTrack.Contracts.GetUserReply> GetUser(
        FinTrack.Contracts.GetUserRequest request,
        ServerCallContext context)
    {
        _logger.LogInformation("gRPC GetUser called for {UserId}", request.UserId);

        if (!Guid.TryParse(request.UserId, out var userId))
            return new FinTrack.Contracts.GetUserReply { Found = false };

        var user = await _db.Users.FirstOrDefaultAsync(u => u.Id == userId);

        if (user is null)
            return new FinTrack.Contracts.GetUserReply { Found = false };

        return new FinTrack.Contracts.GetUserReply
        {
            Found     = true,
            UserId    = user.Id.ToString(),
            Email     = user.Email,
            FirstName = user.FirstName,
        };
    }
}
